### ISSUE TITLE
this.$store is undefined in supplies

### ISSUE THREAD

**Issue by SebT** [Akryum/vue-supply#11]
Hi,

I'm trying out the lib (with vuex & vue-apollo) everything works fine except that I can't access the vuex store from the supplies because `this.$store` is undefined.

Is it by design? 

PS: I did use `injectSupply` to instantiate my vuex store.

**Comment by SebT** [comment]
Alright I went through the source code and notice that supplies are instantiated with a `new Vue(def)`.

So I did a small test with mixins in a component :
```javascript
import Vue from 'vue';

const Test = {
	beforeCreate () {
		console.log('test', this.$store);
	}
};

const Test2 = new Vue({
	beforeCreate () {
		console.log('test2', this.$store);
	}
});

// Use `mixins: [Test, Test]` in a component
```

This prints "test" with the store but "test2" with `undefined`.

Any idea on how to inject the store ?

**Comment by Akryum** [comment]
Did you try this in the supply definition:

```js
import store from '../vuex/store'

export default {
  store,
  ...
}
```

**Comment by SebT** [comment]
Yes I guess I'll have to do this, the same way we inject `apolloProvider`.

It just won't be that easy because my store is instantiated in a function so I can't just import it like this. But I'll find a work around.
