### ISSUE TITLE
Not working with vue-apollo 3 ?

### ISSUE THREAD

**Issue by SebT** [Akryum/vue-supply#14]
Hi,

I'm using currently sing vue-apollo 2 with vue-supply and everything works fine. 

But I'm trying to migrate to vue-apollo 3 so I've updated the code base and everything works fine, except for my supplies using vue-apollo.

Here is a simplified exemple of supply that worked with vue-apollo 2:
```javascript
import { Supply } from 'vue-supply';
import { provider as apolloProvider } from '@/apollo'; // Most basic instance of vue-apollo provider

export default function (store) {
	return {
		extends: Supply,
		store,
		apolloProvider,
		apollo: {
                        $subscribe: {
                            example: { 
                                query: /* GQL subscription query */,
				variables () {
					console.log('This is logged with vue-apollo 2, but not vue-apolo 3');
					return {
						foo: 'bar'
					};
				}
                            }
                        }
			$skipAll () {
				return !this.active;
			}
		}
	};
}
```

In the example above, I replaced the line `apolloProvider,` with -> `provide: apolloProvider.provide(),`, the same way we pass the apollo provider to our vue app instance. 

But when I log the supply in a components that uses it (like `console.log(this.$supply.mySupplierName)`, its `$apolloProvider` prop is null. Which explains why the `apollo` key in supply definition is totally ignored.

Am I forgetting something ? Why does my supply can't have a apollo provider ?

**Comment by Akryum** [comment]
This seems to be related to https://github.com/Akryum/vue-apollo/issues/319

**Comment by SebT** [comment]
I've checked the issue and it seems to be related indeed. I have a small intuition that it's caused by the use of provide / inject mechanism but I'm just speculating.

So I've tried a workaround by calling `this.$apollo.addSmartSubscription` on the `created` hook. The `variables` function is called (I see my `console.log`), but the I get an error. Maybe the output will help you identify the bug:

```
TypeError: Cannot read property 'defaultClient' of null
    at DollarApollo.getClient (vue-apollo.esm.js?522d:1088)
    at DollarApollo.subscribe (vue-apollo.esm.js?522d:1121)
    at SmartSubscription.executeApollo (vue-apollo.esm.js?522d:1024)
    at Vue.$watch (vue.runtime.esm.js?2b0e:3609)
    at SmartSubscription.start (vue-apollo.esm.js?522d:466)
    at SmartSubscription.set$$1 (vue-apollo.esm.js?522d:647)
    at SmartSubscription.skipChanged (vue-apollo.esm.js?522d:408)
    at Watcher.run (vue.runtime.esm.js?2b0e:3229)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:2977)
    at Array.eval (vue.runtime.esm.js?2b0e:1833)
```
